deployment:
    image: quay.io/riotkit/infracheck
    version: v2.1.2-x86_64
    replicas: 1
    imagePullSecrets: []
    podSecurityContext: {}
    environment:
        AUTHORS: https://github.com/riotkit-org
    labels: {}
    nodeSelector: {}
    affinity: {}
    tolerations: []
    annotations: {}
    resources:
        requests:
            memory: "128Mi"
            cpu: "0"
        limits:
            memory: "512Mi"
            cpu: "4"


ingress:
    enabled: true
    host: health.example.org

checks:
    scripts:
        # example - later use it in field "type".
        #
        # {
        #     "type": "hello.sh",
        #     "input": {
        #         "word": "Cheese"
        #     }
        # }
        hello.sh: |
            #!/bin/bash

            echo "Hello! This is an example check, you can write your own 'check' scripts that takes parameters from JSON and environment variables"
            echo "The word is: ${WORD}"
            env

            exit 0

    configured: {}
#        disk-space: |
#              {
#                  "type": "disk-space",
#                  "input": {
#                      "dir": "/",
#                      "min_req_space": "6"
#                  }
#              }
