---
apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-http
spec:
    selector:
        app: {{ .Release.Name }}
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8000

{{ if .Values.ingress.enabled }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
    name: {{ .Release.Name }}
spec:
    entryPoints:
        - websecure
    routes:
        - kind: Rule
          match: Host(`{{ .Values.ingress.host }}`)
          priority: 10
          services:
              - name: {{ .Release.Name }}-http
                port: 80
    tls:
        certResolver: default
{{ end }}
